### ISSUE TITLE
Error: Unimplemented type: 3

### ISSUE THREAD

**Issue by wboykinm** [mapbox/geobuf#61]
I'm making a fairly simple call to the Mapbox API in a node script, and it's failing to decode the response [given use of the geobuf example](https://github.com/wboykinm/tribes/blob/master/processing/water/get.js#L29). Logging the `body` shows a valid, still-encoded response has come back from the API, but attempting to decode throws this:

```
/Users/wboykinm/github/tribes/processing/water/node_modules/pbf/index.js:204
        else throw new Error('Unimplemented type: ' + type);
                   ^
Error: Unimplemented type: 3
    at Object.Pbf.skip (/Users/wboykinm/github/tribes/processing/water/node_modules/pbf/index.js:204:20)
    at Object.Pbf.readFields (/Users/wboykinm/github/tribes/processing/water/node_modules/pbf/index.js:40:45)
    at Object.decode (/Users/wboykinm/github/tribes/processing/water/node_modules/geobuf/decode.js:17:19)
    at Request._callback (/Users/wboykinm/github/tribes/processing/water/get.js:29:26)
    at Request.self.callback (/Users/wboykinm/github/tribes/processing/water/node_modules/request/request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/wboykinm/github/tribes/processing/water/node_modules/request/request.js:1036:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/wboykinm/github/tribes/processing/water/node_modules/request/request.js:963:12)
    at IncomingMessage.emit (events.js:129:20)
```

Am I missing some basic preprocessing of the API response?

**Comment by wboykinm** [comment]
Many thanks to @ericfischer for helping me realize this was a complete misunderstanding of geobuf's purpose; switching over to [`vector-tile-js`](https://github.com/mapbox/vector-tile-js).

**Comment by DenisCarriere** [comment]
@wboykinm Can you expand on the explanation that @ericfischer gave you. I'm having this issue as well, I'll go ahead and use `vector-tile-js` instead of `geobuf`.

**Comment by DenisCarriere** [comment]
Found the issue, the buffer data wasn't unziped.

Found some code that helped out.
```javascript
var zlib = require('zlib');

zlib.gunzip(data, function(err, buffer) {
    var tile = new VectorTile(new Protobuf(buffer));
});
```
