### ISSUE TITLE
geobuf2json failed，this is bug

### ISSUE THREAD

**Issue by coyotey** [mapbox/geobuf#72]
json2geobuf water.json > data.pbf    success！
geobuf2json data.pbf > water.json  is failed!

C:\Users\admin\AppData\Roaming\npm\node_modules\geobuf\node_modules\pbf\index.js:191
      else throw new Error('Unimplemented type: ' + type);
Error: Unimplemented type: 7
     at Object.Pbf.skip (C:\Users\admin\AppData\Roaming\npm\node_modules\geobuf\node_modules\pbf\index.js:191:20)
    at Object.Pbf.readFields (C:\Users\admin\AppData\Roaming\npm\node_modules\geobuf\node_modules\pbf\index.js:41:45)
   at decode (C:\Users\admin\AppData\Roaming\npm\node_modules\geobuf\decode.js:17:19)
at C:\Users\admin\AppData\Roaming\npm\node_modules\geobuf\bin\geobuf2json:12:16
at ConcatStream.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\geobuf\node_modules\concat-stream\index.js:36:43)
at emitNone (events.js:72:20)
at ConcatStream.emit (events.js:166:7)
    at finishMaybe (C:\Users\admin\AppData\Roaming\npm\node_modules\geobuf\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:475
:14)
    at endWritable (C:\Users\admin\AppData\Roaming\npm\node_modules\geobuf\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:485
:3)
    at ConcatStream.Writable.end (C:\Users\admin\AppData\Roaming\npm\node_modules\geobuf\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_w
ritable.js:455:41)

**Comment by mourner** [comment]
Can you provide the GeoJSON sample that failed for you? This is not enough information to find the issue.

**Comment by coyotey** [comment]
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "uuid": "de8de58b-ed7e-49ba-a979-0f93b02290da", "name_chn": " " }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 108.949570159000075, 28.265925881000044 ], [ 108.949457912000071, 28.265888360000076 ], [ 108.949295760000041, 28.265928358000053 ], [ 108.949163544000044, 28.266089967000028 ], [ 108.94907358100005, 28.266152557000055 ], [ 108.948813537000035, 28.266247890000045 ], [ 108.94867312100007, 28.266416486000026 ], [ 108.948315053000044, 28.266574280000043 ], [ 108.948209370000086, 28.266615237000053 ], [ 108.948159876000034, 28.266671391000045 ], [ 108.948100261000036, 28.266834231000075 ], [ 108.948070578000056, 28.267118681000056 ], [ 108.948089978000041, 28.267368342000054 ], [ 108.948185676000037, 28.267426950000072 ], [ 108.94834686300004, 28.267436797000073 ], [ 108.94847674600004, 28.267396250000047 ], [ 108.948567121000053, 28.267312293000032 ], [ 108.94868333900007, 28.267143287000067 ], [ 108.948943109000083, 28.26706219600004 ], [ 108.949125368000068, 28.266815947000055 ], [ 108.949264965000054, 28.266690082000025 ], [ 108.94930899700006, 28.266498484000067 ], [ 108.949359041000037, 28.266413847000024 ], [ 108.949448732000064, 28.266365500000063 ], [ 108.949635224000076, 28.26631879200005 ], [ 108.949693607000086, 28.266220047000047 ], [ 108.949703729000078, 28.266113361000066 ], [ 108.949681037000062, 28.26603461600007 ], [ 108.949570159000075, 28.265925881000044 ] ] ] ] } },
{ "type": "Feature", "properties": { "uuid": "424dfc9b-6276-492b-b6ff-d3448e9744f3", "name_chn": " " }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 108.991305824000051, 28.561131475000025 ], [ 108.990900202000034, 28.561024899000074 ], [ 108.990765499000076, 28.561048437000068 ], [ 108.99075547800004, 28.561144751000029 ], [ 108.990810100000033, 28.561285428000076 ], [ 108.990961577000064, 28.561498381000035 ], [ 108.991140861000076, 28.561626857000078 ], [ 108.991242957000054, 28.561681963000069 ], [ 108.991544158000067, 28.561855809000065 ], [ 108.991841321000038, 28.561898521000046 ], [ 108.992143526000064, 28.561934130000054 ], [ 108.992317362000051, 28.56191848900005 ], [ 108.992401986000061, 28.561859503000051 ], [ 108.992455263000068, 28.56172650700006 ], [ 108.992402306000088, 28.561584424000046 ], [ 108.99216268300006, 28.561443352000026 ], [ 108.991727103000073, 28.561275767000041 ], [ 108.991305824000051, 28.561131475000025 ] ] ] ] } },
{ "type": "Feature", "properties": { "uuid": "62ec0754-48a4-4c3f-8285-7af3ca2cddaa", "name_chn": " " }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 108.994475715000078, 28.598307244000068 ], [ 108.994299767000086, 28.598258024000074 ], [ 108.994069181000043, 28.598325943000077 ], [ 108.993844725000088, 28.59850199300007 ], [ 108.993647, 28.598822546000065 ], [ 108.993497458000036, 28.599192929000026 ], [ 108.993408411000075, 28.599568701000067 ], [ 108.993420637000042, 28.600044211000068 ], [ 108.993461076000074, 28.600415080000062 ], [ 108.993544110000073, 28.600613159000034 ], [ 108.993603207000035, 28.600691980000079 ], [ 108.993717090000075, 28.600732166000057 ], [ 108.993806580000069, 28.600708739000027 ], [ 108.993880191000073, 28.600681773000076 ], [ 108.993920864000074, 28.600610481000047 ], [ 108.994118739000044, 28.60045412900007 ], [ 108.994289264000088, 28.600186381000071 ], [ 108.994366944000035, 28.599977476000049 ], [ 108.994477183000072, 28.599606403000053 ], [ 108.994530689000044, 28.599119092000024 ], [ 108.994603227000084, 28.59866381300003 ], [ 108.994594265000046, 28.598446177000028 ], [ 108.994475715000078, 28.598307244000068 ] ] ] ] } },
{ "type": "Feature", "properties": { "uuid": "c311c054-442f-4a9b-91bb-2e1f3e6bd0d3", "name_chn": "自然公园" }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 106.488331170000038, 29.507786242000066 ], [ 106.487645152000084, 29.507016415000066 ], [ 106.486830904000044, 29.506343394000055 ], [ 106.484450847000062, 29.504481952000049 ], [ 106.484308867000038, 29.504486970000073 ], [ 106.484160667000083, 29.504483831000073 ], [ 106.483815253000046, 29.504533835000075 ], [ 106.483681477000061, 29.504634712000041 ], [ 106.483534620000057, 29.504799689000038 ], [ 106.483432865000054, 29.504891196000074 ], [ 106.483221566000054, 29.504914796000037 ], [ 106.483022338000069, 29.504915362000077 ], [ 106.482954039000049, 29.504978363000077 ], [ 106.482958690000032, 29.505004912000061 ], [ 106.48399719300005, 29.505508950000035 ], [ 106.484407458000078, 29.505179763000058 ], [ 106.485144796000043, 29.505827254000053 ], [ 106.485202521000076, 29.505955756000048 ], [ 106.485183254000049, 29.506052287000045 ], [ 106.484644751000076, 29.506491178000033 ], [ 106.484426814000074, 29.507366563000062 ], [ 106.484600893000049, 29.507394719000047 ], [ 106.484872292000034, 29.507363001000044 ], [ 106.487055827000063, 29.507876524000039 ], [ 106.487183591000075, 29.508014671000069 ], [ 106.487536191000061, 29.508039379000024 ], [ 106.487875992000056, 29.508044836000067 ], [ 106.488061898000069, 29.508005724000043 ], [ 106.488202934000071, 29.507921678000059 ], [ 106.488331170000038, 29.507786242000066 ] ] ] ] } }
]
}

**Comment by albfan** [comment]
I convert the source example to pbf and back and all work. So the data might not represent the problem.

But I use osm data from my region and was able to reproduce:

```
$ wget http://download.geofabrik.de/europe/spain/asturias-latest.osm.pbf
$ geobuf2json asturias-latest.osm.pbf > asturias.geojson
/usr/local/lib/node_modules/geobuf/node_modules/pbf/index.js:211
        else throw new Error('Unimplemented type: ' + type);
             ^

Error: Unimplemented type: 7
    at Pbf.skip (/usr/local/lib/node_modules/geobuf/node_modules/pbf/index.js:211:20)
    at Pbf.readFields (/usr/local/lib/node_modules/geobuf/node_modules/pbf/index.js:46:45)
    at Pbf.readMessage (/usr/local/lib/node_modules/geobuf/node_modules/pbf/index.js:52:21)
    at readFeatureCollection (/usr/local/lib/node_modules/geobuf/decode.js:37:16)
    at readDataField (/usr/local/lib/node_modules/geobuf/decode.js:29:25)
    at Pbf.readFields (/usr/local/lib/node_modules/geobuf/node_modules/pbf/index.js:44:13)
    at decode (/usr/local/lib/node_modules/geobuf/decode.js:18:19)
    at /usr/local/lib/node_modules/geobuf/bin/geobuf2json:12:16
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/geobuf/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (node:events:532:35)
```

is it possible to ignore that somehow and continue?

**Comment by albfan** [comment]
Seems https://github.com/mapbox/geobuf/issues/67 refers to be incompatible with pbf3.

How do we change that version?
